"""Add constraints, cascade, indexes

Revision ID: dafdc7139bee
Revises: 3afa9a64fd34
Create Date: 2026-05-19 14:58:44.945099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dafdc7139bee'
down_revision: Union[str, Sequence[str], None] = '3afa9a64fd34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_department_parent_name', 'departments', ['parent_id', 'name'])
    op.drop_constraint(op.f('departments_parent_id_fkey'), 'departments', type_='foreignkey')
    op.create_foreign_key(None, 'departments', 'departments', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('employees_department_id_fkey'), 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('employees_department_id_fkey'), 'employees', 'departments', ['department_id'], ['id'])
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.create_foreign_key(op.f('departments_parent_id_fkey'), 'departments', 'departments', ['parent_id'], ['id'])
    op.drop_constraint('uq_department_parent_name', 'departments', type_='unique')
    # ### end Alembic commands ###
